name = "nooma-glow-website"
pages_build_output_dir = "dist"

[build]
command = "bun install && bun run build"

[env.production]
compatibility_date = "2024-01-01"

[env.preview]
compatibility_date = "2024-01-01"